FROM fluent/fluentd:v1.14-debian

USER root

ENV FLUENT_UID=0

RUN gem install fluent-plugin-kafka --no-document --version 0.12.1

RUN mkdir -p /fluentd/buffer/kafka \
    && chown -R fluent:fluent /fluentd/buffer

COPY fluent.conf /fluentd/etc/

USER fluent
