FROM confluentinc/cp-kafka:6.2.0

# Copy custom configurations
COPY server.properties /etc/kafka/server.properties

# Expose Kafka port
EXPOSE 9092

# Command to run Kafka
CMD ["/etc/confluent/docker/run"]
